name: CI

on:
  push:
    branches:
      - main  # ou o nome do seu ramo principal
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # ou a versão que você está usando

    - name: Instalar Dependências
      run: npm install

    - name: Executar Testes
      run: npm test

